import type { Metadata } from "next";
import { NextIntlClientProvider, hasLocale } from "next-intl";
import { Oxanium } from "next/font/google";
import { notFound } from "next/navigation";

import "./globals.css";
import { routing } from "@/i18n/routing";
import { ThemeProvider } from "@/providers/theme-provider";

const geistOxanium = Oxanium({
	variable: "--font-oxanium",
	subsets: ["latin"]
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

export default async function RootLayout({
	children,
	params
}: Readonly<{
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}>) {
	const { locale } = await params;
	if (!hasLocale(routing.locales, locale)) {
		notFound();
	}
	return (
		<html lang={locale} suppressHydrationWarning>
			<body className={`${geistOxanium.variable} antialiased`} suppressHydrationWarning>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<NextIntlClientProvider>{children}</NextIntlClientProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}

